# Generated by Django 3.1.3 on 2020-11-29 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_medico',
            name='medico',
            field=models.ManyToManyField(related_name='modifica', to='user.medico'),
        ),
        migrations.AddField(
            model_name='historial_medico',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
    ]
