# Generated by Django 3.1.3 on 2020-11-17 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=60)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('precio', models.CharField(max_length=10)),
                ('subtotal', models.CharField(max_length=10)),
                ('tipo_pago', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=50)),
                ('dni_paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.paciente')),
            ],
        ),
    ]
