# Generated by Django 3.0 on 2020-12-01 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('pedido', '0003_auto_20201130_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.tecnico'),
        ),
    ]
