# Generated by Django 3.0 on 2020-11-30 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='turnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('asistencia', models.BooleanField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.secretaria')),
            ],
        ),
    ]
