# Generated by Django 3.1.3 on 2020-11-29 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turnos', '0001_initial'),
        ('user', '0001_initial'),
        ('paciente', '0002_auto_20201129_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnos',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.medico'),
        ),
        migrations.AddField(
            model_name='turnos',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
        migrations.AddField(
            model_name='turnos',
            name='secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.secretaria'),
        ),
    ]
