# Generated by Django 3.0 on 2020-12-02 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnos',
            name='secretaria',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.secretaria'),
        ),
    ]
